In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\prasa\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prasa\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prasa\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prasa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prasa\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prasa\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
data=pd.read_csv(r"C:\Users\prasa\Downloads\trends.csv")

In [3]:
data.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [4]:
data.head(50)

   location  year            category  rank              query
0    Global  2001     Consumer Brands     1              Nokia
1    Global  2001     Consumer Brands     2               Sony
2    Global  2001     Consumer Brands     3                BMW
3    Global  2001     Consumer Brands     4               Palm
4    Global  2001     Consumer Brands     5              Adobe
5    Global  2001                 Men     1        Nostradamus
6    Global  2001                 Men     2    Osama bin Laden
7    Global  2001                 Men     3             Eminem
8    Global  2001                 Men     4    Michael Jackson
9    Global  2001                 Men     5       Howard Stern
10   Global  2001              Movies     1       Harry Potter
11   Global  2001              Movies     2  Lord of the Rings
12   Global  2001              Movies     3      Final Fantasy
13   Global  2001              Movies     4        Tomb Raider
14   Global  2001              Movies     5              Shrek
15   Global  2001  MP3 Music Services     1           Morpheus
16   Global  2001  MP3 Music Services     2            Napster
17   Global  2001  MP3 Music Services     3           Gnutella
18   Global  2001  MP3 Music Services     4              Kazaa
19   Global  2001  MP3 Music Services     5        Audiogalaxy
20   Global  2001        Music Groups     1            Beatles
21   Global  2001        Music Groups     2                 U2
22   Global  2001        Music Groups     3             N Sync
23   Global  2001        Music Groups     4    Backstreet Boys
24   Global  2001        Music Groups     5        Linkin Park
25   Global  2001        New Products     1         Windows XP
26   Global  2001        New Products     2               Xbox
27   Global  2001        New Products     3      PlayStation 2
28   Global  2001        New Products     4           GameCube
29   Global  2001        New Products     5         Nokia 5510
30   Global  2001      News Resources     1                CNN
31   Global  2001      News Resources     2                BBC
32   Global  2001      News Resources     3     New York Times
33   Global  2001      News Resources     4              MSNBC
34   Global  2001      News Resources     5    Washington Post
35   Global  2001           Retailers     1             Amazon
36   Global  2001           Retailers     2               IKEA
37   Global  2001           Retailers     3        Toys "R" Us
38   Global  2001           Retailers     4            Walmart
39   Global  2001           Retailers     5       Circuit City
40   Global  2001              Sports     1    Anna Kournikova
41   Global  2001              Sports     2     Tour de France
42   Global  2001              Sports     3     Dale Earnhardt
43   Global  2001              Sports     4          Wimbledon
44   Global  2001              Sports     5            US Open
45   Global  2001            TV Shows     1         Loft Story
46   Global  2001            TV Shows     2        Big Brother
47   Global  2001            TV Shows     3       The Simpsons
48   Global  2001            TV Shows     4           Survivor
49   Global  2001            TV Shows     5       Gran Hermano

In [5]:
data

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]

In [6]:
data.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [7]:
data.shape

(26955, 5)

In [8]:
data.info

<bound method DataFrame.info of       location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]>

In [9]:
data.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [10]:
data.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='object')

In [11]:
data.dtypes

location    object
year         int64
category    object
rank         int64
query       object
dtype: object

In [12]:
data.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [13]:
data.duplicated().sum()

np.int64(10)

In [14]:
data.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [21]:
data.drop_duplicates(inplace=True)

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26945 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26945 non-null  object
 1   year      26945 non-null  int64
 2   category  26945 non-null  object
 3   rank      26945 non-null  int64
 4   query     26945 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.2+ MB